// GPU Tilemaps — the map is a TEXTURE of tile ids; one fullscreen fragment shader turns every screen
// pixel into (tile, pixel-inside-tile), reads the id, and fetches the right texel from a tileset.
// The whole layer is one draw call no matter how big the map is.
//   rpg      : top-down map with animated water, shore foam (neighbour lookups), decoration layer, tree objects
//   autotile : side-scroller terrain whose tile variant is computed in the shader from a 4- or 8-bit neighbour mask
//   huge     : a 4096×4096 map generated by a COMPUTE shader, with LOD (average tile colour) when zoomed far out

import { SpriteBatch, ShapeBatch, Camera2D } from '../../core/batch.js';
import { makeCanvas, rng } from '../../core/assets.js';
import { atlasTexture, tag, fmt, clamp, DIGITS_WGSL } from './_shared.js';

const TS = 16; // tile size in texels

// ---------------------------------------------------------------- tileset ids
const ID = {
  VOID: 0, GRASS: 1, SAND: 4, PATH: 5, STONE: 6, SNOW: 7, WATER: 8, DEEP: 12, FOREST: 16, MEADOW: 17,
  MOUNTAIN: 18, BRICK: 19, LAVA: 20, WOOD: 24, SIDE: 25,
  BUSH: 32, FLOWER: 33, ROCK: 34, MUSHROOM: 35, CRATE: 36, CHEST: 37,
};
const NAMES = {
  0: 'void', 1: 'grass', 2: 'grass (variant)', 3: 'grass (variant)', 4: 'sand', 5: 'path', 6: 'stone', 7: 'snow',
  8: 'water', 9: 'water', 10: 'water', 11: 'water', 12: 'deep water', 13: 'deep water', 14: 'deep water', 15: 'deep water',
  16: 'forest floor', 17: 'meadow', 18: 'mountain', 19: 'brick', 20: 'lava', 24: 'wood', 25: 'grass block',
  32: 'bush', 33: 'flower', 34: 'rock', 35: 'mushroom', 36: 'crate', 37: 'chest',
};

function hashXY(x, y, s) {
  let h = (x * 374761393 + y * 668265263 + s * 2147483647) | 0;
  h = Math.imul(h ^ (h >>> 13), 1274126177);
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
}

function buildTileset(atlas) {
  const c = makeCanvas(256, 64);
  const g = c.getContext('2d');
  g.imageSmoothingEnabled = false;
  const at = (id) => [(id % 16) * TS, Math.floor(id / 16) * TS];
  const put = (id, name) => {
    const f = atlas.frames[name];
    const [x, y] = at(id);
    g.drawImage(atlas.canvas, f.x, f.y, f.w, f.h, x, y, TS, TS);
  };
  const paint = (id, fn) => {
    const [ox, oy] = at(id);
    for (let y = 0; y < TS; y++)
      for (let x = 0; x < TS; x++) {
        g.fillStyle = fn(x, y);
        g.fillRect(ox + x, oy + y, 1, 1);
      }
  };
  const noisy = (seed, base, dark, light, dd = 0.18, ll = 0.1) => (x, y) => {
    const r = hashXY(x, y, seed);
    return r < dd ? dark : r > 1 - ll ? light : base;
  };
  paint(ID.VOID, () => '#0d1020');
  for (let v = 0; v < 3; v++) {
    paint(ID.GRASS + v, (x, y) => {
      const r = hashXY(x, y, 11 + v);
      // little "v" tufts
      const tuft = hashXY(Math.floor(x / 4), Math.floor(y / 4), 50 + v) > 0.6 && (x % 4 === 1 || x % 4 === 3) && y % 4 === 1;
      const tuftC = hashXY(Math.floor(x / 4), Math.floor(y / 4), 50 + v) > 0.6 && x % 4 === 2 && y % 4 === 2;
      if (tuft) return '#7fd06a';
      if (tuftC) return '#2f8f4e';
      return r < 0.16 ? '#3e9e52' : r > 0.92 ? '#5cc46a' : '#4cb05c';
    });
  }
  put(ID.SAND, 'tile_sand');
  paint(ID.PATH, noisy(21, '#b98b5a', '#9a6a43', '#d2a774', 0.2, 0.12));
  put(ID.STONE, 'tile_stone');
  paint(ID.SNOW, noisy(31, '#e8f1f8', '#c4d6e8', '#ffffff', 0.15, 0.12));
  for (let i = 0; i < 4; i++) put(ID.WATER + i, `tile_water_${i}`);
  // deep water = darker copy of the water frames
  for (let i = 0; i < 4; i++) {
    const [sx, sy] = at(ID.WATER + i);
    const [dx, dy] = at(ID.DEEP + i);
    const img = g.getImageData(sx, sy, TS, TS);
    for (let k = 0; k < img.data.length; k += 4) {
      img.data[k] *= 0.55;
      img.data[k + 1] *= 0.62;
      img.data[k + 2] *= 0.8;
    }
    g.putImageData(img, dx, dy);
  }
  paint(ID.FOREST, noisy(41, '#2a7a57', '#1f5e4a', '#3a9462', 0.25, 0.12));
  paint(ID.MEADOW, (x, y) => {
    const f = hashXY(Math.floor(x / 5), Math.floor(y / 5), 77);
    if (f > 0.55 && x % 5 === 2 && y % 5 === 2) return f > 0.8 ? '#f59bb5' : '#ffcd75';
    const r = hashXY(x, y, 17);
    return r < 0.16 ? '#3e9e52' : r > 0.92 ? '#5cc46a' : '#4cb05c';
  });
  paint(ID.MOUNTAIN, (x, y) => {
    const r = hashXY(x, y, 18);
    const crack = (x + y * 2) % 11 === 0 || (x * 3 - y) % 13 === 0;
    return crack ? '#3f4a5e' : r < 0.2 ? '#566c86' : r > 0.9 ? '#94b0c2' : '#6e7f96';
  });
  put(ID.BRICK, 'tile_brick');
  for (let i = 0; i < 4; i++) put(ID.LAVA + i, `tile_lava_${i}`);
  put(ID.WOOD, 'tile_wood');
  put(ID.SIDE, 'tile_grass');
  put(ID.BUSH, 'bush');
  put(ID.FLOWER, 'flower');
  put(ID.ROCK, 'rock');
  put(ID.MUSHROOM, 'mushroom');
  put(ID.CRATE, 'crate');
  put(ID.CHEST, 'chest');
  // average colour per tile (used for far-zoom LOD)
  const avg = new Float32Array(32 * 4);
  for (let id = 0; id < 32; id++) {
    const [x, y] = at(id);
    const d = g.getImageData(x, y, TS, TS).data;
    let r = 0;
    let gg = 0;
    let b = 0;
    for (let k = 0; k < d.length; k += 4) {
      r += d[k];
      gg += d[k + 1];
      b += d[k + 2];
    }
    const n = (d.length / 4) * 255;
    avg.set([r / n, gg / n, b / n, 1], id * 4);
  }
  return { canvas: c, avg };
}

// ---------------------------------------------------------------- autotile set (256 neighbour masks)
// bits: N=1 E=2 S=4 W=8 NE=16 SE=32 SW=64 NW=128. Each 16×16 tile is painted from four 8×8 quadrants:
// a quadrant only cares about its two orthogonal neighbours and the diagonal between them.
function buildAutotiles(atlas) {
  const c = makeCanvas(256, 256);
  const g = c.getContext('2d');
  const f = atlas.frames.tile_dirt;
  const dirt = atlas.canvas.getContext('2d').getImageData(f.x, f.y, 16, 16).data;
  const img = g.createImageData(256, 256);
  const GH = [4, 5, 4, 3, 4, 5, 5, 4, 3, 4, 5, 4, 4, 3, 4, 5];
  const hex = (h) => [parseInt(h.slice(1, 3), 16), parseInt(h.slice(3, 5), 16), parseInt(h.slice(5, 7), 16), 255];
  const OUT = hex('#2b1a12');
  const OUTG = hex('#173b2e');
  const G1 = hex('#a7f070');
  const G2 = hex('#38b764');
  const G3 = hex('#23735a');
  const CLEAR = [0, 0, 0, 0];
  for (let m = 0; m < 256; m++) {
    const N = m & 1;
    const E = m & 2;
    const S = m & 4;
    const Wb = m & 8;
    for (let y = 0; y < 16; y++)
      for (let x = 0; x < 16; x++) {
        const top = y < 8;
        const left = x < 8;
        const vOpen = top ? !N : !S;
        const hOpen = left ? !Wb : !E;
        const dBit = top ? (left ? 128 : 16) : left ? 64 : 32;
        const dOpen = !(m & dBit);
        const dy = top ? y : 15 - y;
        const dx = left ? x : 15 - x;
        const k = (y * 16 + x) * 4;
        let col = [dirt[k], dirt[k + 1], dirt[k + 2], 255];
        const shade = (s) => (col = [col[0] * s, col[1] * s, col[2] * s, 255]);
        if (hOpen && dx === 1) shade(0.72);
        if (hOpen && dx === 2) shade(0.88);
        if (vOpen && !top && dy === 1) shade(0.6);
        if (vOpen && !top && dy === 2) shade(0.8);
        const grassy = vOpen && top && dy <= GH[x];
        if (grassy) col = dy === 0 ? OUTG : dy === 1 ? G1 : dy === GH[x] ? G3 : G2;
        if (hOpen && dx === 0) col = grassy || (vOpen && top && dy <= 4) ? OUTG : OUT;
        if (vOpen && dy === 0) col = top ? OUTG : OUT;
        if (vOpen && hOpen) {
          if (dx + dy < 2) col = CLEAR;
          else if (dx + dy === 2) col = top ? OUTG : OUT;
        }
        if (!vOpen && !hOpen && dOpen) {
          // inner (concave) corner: the 8-bit set's extra tiles
          if (top) {
            if (dx + dy === 0) col = OUTG;
            else if (dx + dy <= 2) col = G2;
            else if (dx + dy === 3) col = G3;
          } else if (dx + dy <= 1) col = OUT;
          else if (dx + dy === 2) shade(0.6);
        }
        const ox = (m % 16) * 16 + x;
        const oy = Math.floor(m / 16) * 16 + y;
        img.data.set(col.map(Math.round), (oy * 256 + ox) * 4);
      }
  }
  g.putImageData(img, 0, 0);
  return c;
}

// ---------------------------------------------------------------- JS value noise (for the small maps)
function makeNoise(seed) {
  const h = (x, y) => hashXY(x, y, seed);
  const sm = (t) => t * t * (3 - 2 * t);
  const vn = (x, y) => {
    const xi = Math.floor(x);
    const yi = Math.floor(y);
    const fx = sm(x - xi);
    const fy = sm(y - yi);
    const a = h(xi, yi);
    const b = h(xi + 1, yi);
    const c = h(xi, yi + 1);
    const d = h(xi + 1, yi + 1);
    return a + (b - a) * fx + (c - a) * fy + (a - b - c + d) * fx * fy;
  };
  return (x, y, oct = 4) => {
    let s = 0;
    let amp = 0.5;
    let norm = 0;
    for (let i = 0; i < oct; i++) {
      s += vn(x, y) * amp;
      norm += amp;
      x = x * 2.03 + 17.1;
      y = y * 2.03 + 9.7;
      amp *= 0.5;
    }
    return s / norm;
  };
}

function buildRpgMap(W, H, seed) {
  const data = new Uint8Array(W * H * 4);
  const trees = [];
  const elev = makeNoise(seed);
  const moist = makeNoise(seed + 99);
  const roads = makeNoise(seed + 7);
  const r = rng(seed);
  for (let y = 0; y < H; y++)
    for (let x = 0; x < W; x++) {
      const e = elev(x * 0.035, y * 0.035, 5);
      const m = moist(x * 0.05, y * 0.05, 3);
      let id = ID.GRASS;
      let deco = 0;
      if (e < 0.36) id = ID.DEEP;
      else if (e < 0.43) id = ID.WATER;
      else if (e < 0.47) id = ID.SAND;
      else if (e > 0.72) id = ID.MOUNTAIN;
      else if (e > 0.67) id = ID.STONE;
      else if (m > 0.58) id = ID.FOREST;
      else if (m < 0.38) id = ID.MEADOW;
      const rd = Math.abs(roads(x * 0.03, y * 0.03, 3) - 0.5);
      if (rd < 0.012 && id !== ID.DEEP && id !== ID.WATER && id !== ID.MOUNTAIN) id = ID.PATH;
      if (rd < 0.012 && id === ID.WATER) id = ID.WOOD; // bridges
      const q = r();
      if (id === ID.GRASS || id === ID.MEADOW) {
        if (q < 0.025) deco = ID.FLOWER;
        else if (q < 0.035) deco = ID.BUSH;
        else if (q < 0.04) deco = ID.ROCK;
        else if (q < 0.055) trees.push([x, y]);
      } else if (id === ID.FOREST) {
        if (q < 0.5) trees.push([x, y]);
        else if (q < 0.56) deco = ID.MUSHROOM;
        else if (q < 0.62) deco = ID.BUSH;
      } else if (id === ID.STONE && q < 0.05) deco = ID.ROCK;
      const k = (y * W + x) * 4;
      data[k] = id;
      data[k + 1] = deco;
    }
  // a small brick plaza with a chest
  const px = Math.floor(W * 0.5);
  const py = Math.floor(H * 0.5);
  for (let y = py - 3; y <= py + 3; y++)
    for (let x = px - 4; x <= px + 4; x++) {
      const k = (y * W + x) * 4;
      data[k] = ID.BRICK;
      data[k + 1] = 0;
    }
  data[(py * W + px) * 4 + 1] = ID.CHEST;
  data[((py - 2) * W + px - 3) * 4 + 1] = ID.CRATE;
  data[((py + 2) * W + px + 3) * 4 + 1] = ID.CRATE;
  const filtered = trees.filter(([x, y]) => Math.abs(x - px) > 5 || Math.abs(y - py) > 4);
  return { data, trees: filtered, plaza: [px, py] };
}

function buildSideMap(W, H) {
  const m = new Uint8Array(W * H);
  const set = (x, y, v = 1) => x >= 0 && y >= 0 && x < W && y < H && (m[y * W + x] = v);
  for (let x = 0; x < W; x++) {
    const h = Math.round(11 + 1.6 * Math.sin(x * 0.35) + 0.8 * Math.sin(x * 0.9 + 1));
    for (let y = h; y < H; y++) set(x, y);
  }
  // pits
  for (const px of [16, 17, 39]) for (let y = 0; y < H; y++) set(px, y, 0);
  // floating islands & an overhang with a cave (lots of inner corners)
  for (let x = 6; x <= 11; x++) set(x, 7);
  for (let x = 7; x <= 10; x++) set(x, 8);
  for (let x = 21; x <= 28; x++) for (let y = 5; y <= 6; y++) set(x, y);
  for (let y = 7; y <= 9; y++) set(21, y);
  for (let x = 31; x <= 35; x++) set(x, 8 - (x - 31 > 2 ? 1 : 0));
  for (let x = 44; x <= 52; x++) for (let y = 6; y <= 13; y++) set(x, y);
  for (let x = 46; x <= 50; x++) for (let y = 9; y <= 11; y++) set(x, y, 0);
  for (let x = 56; x <= 60; x++) set(x, 9);
  return m;
}

// ---------------------------------------------------------------- shaders

const MAP_WGSL = /* wgsl */ `
${DIGITS_WGSL}
fn tileTexel(id: i32, t: vec2i) -> vec4f { return LOAD(tiles, vec2i(id % 16, id / 16) * 16 + t); }
fn mapId(t: vec2i) -> i32 {
  if (t.x < 0 || t.y < 0 || t.x >= i32(u.mapSize.x) || t.y >= i32(u.mapSize.y)) { return -1; }
  return i32(round(LOAD(map, t).r * 255.0));
}
fn isWater(id: i32) -> bool { return id >= 8 && id < 16; }
fn isLand(id: i32) -> bool { return id >= 0 && !isWater(id) && id != 24; }
fn animated(id: i32, tile: vec2i) -> i32 {
  if (u.anim < 0.5) { return id; }
  let f = i32(floor(u.time * 4.0));
  if (id >= 8 && id < 16) { return id - id % 4 + f % 4; }
  if (id >= 20 && id < 24) { return 20 + f % 4; }
  return id;
}

// -------- top-down maps (rpg & huge)
fn shadeTiles(world: vec2f) -> vec3f {
  let tile = vec2i(floor(world / 16.0));
  let tex = vec2i(floor(world - vec2f(tile) * 16.0));
  var id = mapId(tile);
  if (id < 0) {
    let w = floor(world / 4.0);
    return mix(vec3f(0.05, 0.06, 0.12), vec3f(0.07, 0.08, 0.15), step(0.5, fract((w.x + w.y) * 0.5)));
  }
  let cell = LOAD(map, tile);
  let deco = i32(round(cell.g * 255.0));
  var drawId = id;
  if (id == 1) { drawId = 1 + i32(floor(hash21(vec2f(tile)) * 2.99)); }   // random variant per tile
  drawId = animated(drawId, tile);
  var c = tileTexel(drawId, tex).rgb;
  // shore foam: a water tile looks at its 4 neighbours (no extra tiles needed)
  if (u.foam > 0.5 && isWater(id)) {
    var d = 99.0;
    if (isLand(mapId(tile + vec2i(0, -1)))) { d = min(d, f32(tex.y)); }
    if (isLand(mapId(tile + vec2i(0, 1)))) { d = min(d, f32(15 - tex.y)); }
    if (isLand(mapId(tile + vec2i(-1, 0)))) { d = min(d, f32(tex.x)); }
    if (isLand(mapId(tile + vec2i(1, 0)))) { d = min(d, f32(15 - tex.x)); }
    let wob = 1.5 + 1.2 * sin(u.time * 2.2 + f32(tile.x * 7 + tile.y * 3) + f32(tex.x + tex.y) * 0.6);
    if (d < wob) { c = mix(c, vec3f(0.92, 0.97, 1.0), 0.85); }
    else if (d < wob + 2.0) { c = mix(c, vec3f(0.55, 0.85, 0.95), 0.45); }
  }
  // decoration layer (second id in the same texel)
  if (deco > 0) {
    let dc = tileTexel(deco, tex);
    c = mix(c, dc.rgb, dc.a);
  }
  // far zoom: one screen pixel covers many texels -> use the tile's average colour (no shimmer)
  if (u.lod > 0.5) {
    var aid = id;
    if (deco > 0 && deco < 32) { aid = deco; }
    let a = u.avg[aid % 32].rgb;
    c = mix(a, c, smoothstep(1.5, 5.0, 16.0 * u.zoom));
  }
  return c;
}

// -------- side-scroller with autotiling
fn solidAt(t: vec2i) -> bool {
  if (t.y >= i32(u.mapSize.y)) { return true; }
  if (t.y < 0) { return false; }
  let x = clamp(t.x, 0, i32(u.mapSize.x) - 1);
  return LOAD(map, vec2i(x, t.y)).r > 0.002;
}
fn autoMask(t: vec2i) -> i32 {
  let n = solidAt(t + vec2i(0, -1));
  let e = solidAt(t + vec2i(1, 0));
  let s = solidAt(t + vec2i(0, 1));
  let w = solidAt(t + vec2i(-1, 0));
  var m = select(0, 1, n) + select(0, 2, e) + select(0, 4, s) + select(0, 8, w);
  if (u.autoMode > 1.5) {
    // 8-bit: a diagonal only matters when both neighbouring sides are filled (256 masks -> 47 tiles)
    if (n && e && solidAt(t + vec2i(1, -1))) { m += 16; }
    if (s && e && solidAt(t + vec2i(1, 1))) { m += 32; }
    if (s && w && solidAt(t + vec2i(-1, 1))) { m += 64; }
    if (n && w && solidAt(t + vec2i(-1, -1))) { m += 128; }
  }
  return m;
}
fn skyAt(px: vec2f, world: vec2f) -> vec3f {
  let uv = px / u.res;
  var c = mix(vec3f(0.36, 0.6, 0.93), vec3f(0.82, 0.9, 0.97), smoothstep(0.0, 0.9, uv.y));
  let x1 = (px.x / u.zoom + u.cam.x * 0.3) * 0.02;
  let h1 = u.res.y * (0.45 + 0.07 * sin(x1) + 0.04 * sin(x1 * 2.7 + 1.0));
  if (px.y > h1) { c = mix(c, vec3f(0.6, 0.74, 0.9), 0.8); }
  let x2 = (px.x / u.zoom + u.cam.x * 0.55) * 0.035;
  let h2 = u.res.y * (0.6 + 0.05 * sin(x2 + 2.0) + 0.03 * sin(x2 * 3.1));
  if (px.y > h2) { c = mix(c, vec3f(0.42, 0.66, 0.6), 0.85); }
  return c;
}
fn shadeSide(world: vec2f, px: vec2f) -> vec3f {
  let tile = vec2i(floor(world / 16.0));
  let tex = vec2i(floor(world - vec2f(tile) * 16.0));
  var c = skyAt(px, world);
  if (!solidAt(tile) || tile.x < 0 || tile.x >= i32(u.mapSize.x)) { return c; }
  var t: vec4f;
  if (u.autoMode < 0.5) {
    t = tileTexel(25, tex);                                          // one tile for everything
  } else {
    var m = autoMask(tile);
    if (u.autoMode < 1.5) { m = m + 240; }                               // 4-bit: pretend all diagonals are filled
    t = LOAD(autoTex, vec2i(m % 16, m / 16) * 16 + tex);
  }
  return mix(c, t.rgb, t.a);
}

fn shade(uv: vec2f, px: vec2f) -> vec4f {
  let world = u.cam + (px - u.res * 0.5) / u.zoom;
  var c: vec3f;
  if (u.mode > 0.5 && u.mode < 1.5) { c = shadeSide(world, px); } else { c = shadeTiles(world); }
  let tile = vec2i(floor(world / 16.0));
  let inT = world - vec2f(tile) * 16.0;
  let tilePx = 16.0 * u.zoom;
  let inside = tile.x >= 0 && tile.y >= 0 && tile.x < i32(u.mapSize.x) && tile.y < i32(u.mapSize.y);
  // grid overlay: 1 screen pixel lines on tile borders
  if (u.grid > 0.5 && tilePx > 5.0 && inside) {
    let e = min(inT.x, inT.y) * u.zoom;
    if (e < 1.0) { c = mix(c, vec3f(0.0), 0.45); }
  }
  // hovered tile
  if (inside && tile.x == i32(u.hover.x) && tile.y == i32(u.hover.y)) {
    let e = min(min(inT.x, inT.y), min(16.0 - inT.x, 16.0 - inT.y)) * u.zoom;
    if (e < 2.0 * max(1.0, u.zoom * 0.25)) { c = vec3f(1.0, 0.85, 0.3); }
    else { c = mix(c, vec3f(1.0, 0.9, 0.5), 0.12); }
  }
  // tile ids (or autotile masks), only when tiles are big enough on screen
  if (u.ids > 0.5 && tilePx >= 22.0 && inside) {
    var n = mapId(tile);
    var show = true;
    if (u.mode > 0.5 && u.mode < 1.5) {
      show = solidAt(tile);
      if (u.autoMode > 0.5) { n = autoMask(tile); } else { n = 25; }
    }
    if (show) {
      let center = (vec2f(tile) + 0.5) * 16.0;
      var fs = 1.6;
      var digits = 1.0;
      if (n >= 10) { digits = 2.0; }
      if (n >= 100) { digits = 3.0; fs = 1.2; }
      let sh = numberMask(n, world - vec2f(1.0, 1.0) / u.zoom, center, fs);
      let body = numberMask(n, world, center, fs);
      let boxD = abs(world - center) - vec2f((digits * 4.0 - 1.0) * fs * 0.5 + fs, 3.5 * fs);
      if (max(boxD.x, boxD.y) < 0.0) { c = mix(c, vec3f(0.0), 0.45); }
      c = mix(c, vec3f(0.0), sh);
      c = mix(c, vec3f(1.0, 0.95, 0.7), body);
    }
  }
  return vec4f(c, 1.0);
}
`;

const GEN_WGSL = /* wgsl */ `
@compute @workgroup_size(8, 8) fn gen(@builtin(global_invocation_id) id: vec3u) {
  let size = u32(g.size);
  if (id.x >= size || id.y >= size) { return; }
  let p = vec2f(id.xy) + g.seed * 137.0;
  // domain-warped fBm continents + moisture
  let warp = vec2f(fbm(p * 0.0021, 3), fbm(p * 0.0021 + vec2f(31.0, 7.0), 3)) * 160.0;
  let e = fbm((p + warp) * 0.0042, 6) * 0.5 + 0.5;
  let m = fbm(p * 0.006 + vec2f(91.0, 13.0), 4) * 0.5 + 0.5;
  let r = hash21(vec2f(id.xy) + g.seed);
  var t = 1.0;
  var deco = 0.0;
  if (e < 0.42) { t = 12.0; }
  else if (e < 0.48) { t = 8.0; }
  else if (e < 0.51) { t = 4.0; }
  else if (e > 0.76) { t = 7.0; }
  else if (e > 0.69) { t = 18.0; }
  else if (e > 0.65) { t = 6.0; }
  else if (m > 0.56) { t = 16.0; if (r < 0.45) { deco = 32.0; } else if (r < 0.5) { deco = 35.0; } }
  else if (m < 0.4) { t = 17.0; if (r < 0.03) { deco = 34.0; } }
  else { if (r < 0.03) { deco = 33.0; } else if (r < 0.04) { deco = 32.0; } }
  // rivers: thin noise contours that cut through land
  let rv = abs(fbm(p * 0.0035 + vec2f(5.0, 50.0), 4));
  if (rv < 0.012 && e > 0.5 && e < 0.69) { t = 8.0; deco = 0.0; }
  // lava pools in the mountains
  if (e > 0.72 && m > 0.62) { t = 20.0; deco = 0.0; }
  textureStore(outTex, vec2i(id.xy), vec4f(t / 255.0, deco / 255.0, e, 1.0));
}
`;

export default {
  keys: true,
  wheel: true,
  interaction: 'Drag to pan · mouse wheel to zoom.',
  examples: [
    {
      id: 'rpg',
      label: 'Top-down RPG',
      kind: 'In a game',
      note: 'A 128×96 map stored as a texture: <b>red = ground tile id</b>, <b>green = decoration id</b>. Water animates by offsetting its id with time, grass picks one of three variants by hashing its position, and shore foam is drawn by looking at neighbouring tiles — all in one fragment shader. Trees are taller than a tile, so they’re separate sprites, sorted by y.',
      hint: 'Drag to pan · wheel to zoom · turn on “Show tile ids”.',
      params: { zoom: 2 },
    },
    {
      id: 'autotile',
      label: 'Side-scroller autotiling',
      kind: 'In a game',
      note: 'The map only stores <b>solid / empty</b>. The shader reads the 4 (or 8) neighbours of each tile, builds a <b>bitmask</b> (N=1, E=2, S=4, W=8, +diagonals 16…128) and uses it to pick the right edge/corner tile. Paint with the left mouse button, erase with the right one. Switch “Autotiling” to see the difference.',
      hint: 'Left-drag paints · right-drag erases · ←/→ scroll.',
    },
    {
      id: 'huge',
      label: 'Huge map (16M tiles)',
      kind: 'Abstract',
      note: 'A 4096 × 4096 tile world (16.7 million tiles, 64 MB) generated by a <b>compute shader</b> in milliseconds, rendered with the same single draw call. Cost depends on screen pixels, not map size. Zoom far out: tiles shrink below a pixel, so the shader switches to each tile’s <b>average colour</b> (a level of detail) instead of shimmering.',
      hint: 'Drag to pan · wheel to zoom far in and out.',
      params: { zoom: 0.12 },
    },
  ],
  controls: [
    { type: 'slider', key: 'zoom', label: 'Zoom', min: 0.01, max: 8, step: 0.01, value: 2, log: true, showFor: ['rpg', 'huge'], help: 'Screen pixels per texel. The mouse wheel zooms around the cursor.' },
    { type: 'toggle', key: 'grid', label: 'Grid overlay', value: false },
    { type: 'toggle', key: 'ids', label: 'Show tile ids', value: false, help: 'The number stored in the map texture (in the autotiling tab: the neighbour bitmask).' },
    { type: 'toggle', key: 'anim', label: 'Animated tiles', value: true, showFor: ['rpg', 'huge'], help: 'Water & lava: id + floor(time × 4) % 4 — no CPU work.' },
    { type: 'toggle', key: 'foam', label: 'Shore foam (neighbour lookup)', value: true, showFor: ['rpg', 'huge'] },
    { type: 'toggle', key: 'trees', label: 'Tree sprites (y-sorted objects)', value: true, showFor: ['rpg'] },
    {
      type: 'select',
      key: 'auto',
      label: 'Autotiling',
      value: '8',
      showFor: ['autotile'],
      options: [
        { value: 'off', label: 'Off — one tile everywhere' },
        { value: '4', label: '4-bit — 16 tiles (edges)' },
        { value: '8', label: '8-bit — 47 tiles (edges + inner corners)' },
      ],
    },
    {
      type: 'select',
      key: 'brush',
      label: 'Left mouse button',
      value: 'paint',
      showFor: ['autotile'],
      options: [
        { value: 'paint', label: 'Paint ground' },
        { value: 'erase', label: 'Erase' },
      ],
    },
    { type: 'button', key: 'reset', label: 'Reset terrain', showFor: ['autotile'] },
    { type: 'toggle', key: 'lod', label: 'Far-zoom LOD (average colour)', value: true, showFor: ['huge'], help: 'Off = sample one texel per pixel: zoomed out the map sparkles and shimmers while panning.' },
    {
      type: 'select',
      key: 'mapSize',
      label: 'Map size',
      value: 4096,
      showFor: ['huge'],
      options: [
        { value: 1024, label: '1024 × 1024 (1M tiles)' },
        { value: 2048, label: '2048 × 2048 (4M tiles)' },
        { value: 4096, label: '4096 × 4096 (16.7M tiles)' },
      ],
    },
    { type: 'slider', key: 'seed', label: 'World seed', min: 1, max: 100, step: 1, value: 7, showFor: ['huge', 'rpg'], help: 'Regenerates the map (on the GPU for the huge map).' },
  ],
  about: {
    summary: 'Instead of thousands of tile sprites, store the map as a texture of tile ids and let one fragment shader draw the whole layer in a single pass — any map size, constant cost.',
    what: `<p>Three tilemaps rendered by the <b>same fragment shader</b>: a top-down RPG map with animated water, shore foam and decorations,
      a side-scroller whose edges are picked automatically from neighbour bitmasks (<b>autotiling</b>), and a 16-million-tile world generated by a compute shader.</p>`,
    how: `<ol>
      <li>The <b>map texture</b> stores one texel per tile: the red channel is the tile id (0–255), green a second layer (decorations).</li>
      <li>The <b>tileset</b> is a texture with all 16×16 tiles in a grid; tile <i>id</i> lives at column <code>id % 16</code>, row <code>id / 16</code>.</li>
      <li>For each screen pixel: <code>world = camera + (pixel − center) / zoom</code> → <code>tile = floor(world / 16)</code>, <code>texel = world mod 16</code>
        → <code>id = map[tile]</code> → <code>color = tileset[idOrigin + texel]</code>. That’s the whole renderer.</li>
      <li><b>Animated tiles</b>: change the id with time inside the shader (water frames 8–11). <b>Variants</b>: add <code>hash(tile) % 3</code> so grass doesn’t repeat.</li>
      <li><b>Autotiling</b>: look at the neighbours, build a bitmask (N=1, E=2, S=4, W=8 → 16 combos). Adding the 4 diagonals gives 256 combos, but a diagonal
        only matters when both adjacent sides are filled, which collapses them to <b>47</b> unique tiles (the “blob” tileset). Our 47 tiles are built from 4 quarter-tiles each.</li>
      <li><b>LOD</b>: when a tile is smaller than a few pixels, use its precomputed average colour — like a mipmap, but per tile id.</li>
    </ol>`,
    uses: [
      { title: 'RPGs & roguelikes', text: 'Pokémon, Stardew Valley, Zelda-likes: terrain layers, animated water, decoration layers.' },
      { title: 'Platformers', text: 'Celeste, Terraria and Dead Cells-style terrain with automatic edges and corners (Godot & Unity call it “terrain/rule tiles”).' },
      { title: 'Strategy & sims', text: 'Huge overworld maps, minimaps and editors where the map changes every frame (just update texels).' },
      { title: 'Level editors', text: 'Paint terrain and let autotiling pick edges — what Tiled, LDtk and engine tile editors do.' },
    ],
    try: [
      'Turn on <b>Show tile ids</b> and <b>Grid</b>, then zoom in on a lake shore in the RPG map.',
      'In <b>Side-scroller</b>, switch <i>Autotiling</i> between Off, 4-bit and 8-bit and look at concave corners (inside the cave).',
      'Paint a single block in the sky: it becomes a little floating island with rounded corners (mask 0).',
      'In <b>Huge map</b>, zoom all the way out, turn off <i>Far-zoom LOD</i> and pan: the shimmer is aliasing.',
      'Change the <i>World seed</i> on the huge map — 16 million tiles regenerate on the GPU instantly.',
    ],
    ask: [
      'a GPU tilemap: tile ids in a texture, one draw call per layer',
      'blob autotiling with an 8-bit neighbour mask (47 tiles)',
      'animated water tiles and shore foam in the tile shader',
      'a huge procedurally generated tile world on the GPU',
      'tile variants chosen by hashing the tile position',
      'LOD for zoomed-out tilemaps (average tile colour)',
    ],
    perf: `<p>Cost = one fullscreen pass with a few texture reads per pixel (3–9 with neighbour lookups) — independent of map size. A sprite-per-tile renderer
      grows with the number of visible tiles and needs CPU culling. The map texture costs 4 bytes per tile (64 MB for 4096²); editing a tile is a 4-byte
      <code>writeTexture</code>.</p>`,
    api: `<p>The tile shader itself works the same in WebGL2 (it’s just texture lookups). WebGPU adds the <b>compute shader</b> that writes the huge map
      straight into a storage texture; in WebGL2 you would generate it in a fragment pass into a render target, or on the CPU.
      (This scene is implemented on WebGPU.)</p>`,
    code: [
      {
        title: 'The whole tile renderer (fragment shader)',
        lang: 'wgsl',
        src: `fn shade(uv: vec2f, px: vec2f) -> vec4f {
  let world = u.cam + (px - u.res * 0.5) / u.zoom;     // pixel -> world
  let tile = vec2i(floor(world / 16.0));               // which tile
  let tex  = vec2i(floor(world - vec2f(tile) * 16.0)); // texel inside it
  var id = i32(round(LOAD(map, tile).r * 255.0));      // tile id from the map texture
  if (id >= 8 && id < 12) { id = 8 + i32(u.time * 4.0) % 4; } // animated water
  let c = LOAD(tiles, vec2i(id % 16, id / 16) * 16 + tex);   // texel from the tileset
  return vec4f(c.rgb, 1.0);
}`,
      },
      {
        title: 'Autotiling: neighbour bitmask',
        lang: 'wgsl',
        src: `var m = select(0, 1, n) + select(0, 2, e) + select(0, 4, s) + select(0, 8, w);
// 8-bit: a diagonal only counts when both neighbouring sides are filled
if (n && e && solidAt(t + vec2i(1, -1))) { m += 16; }
if (s && e && solidAt(t + vec2i(1,  1))) { m += 32; }
if (s && w && solidAt(t + vec2i(-1, 1))) { m += 64; }
if (n && w && solidAt(t + vec2i(-1,-1))) { m += 128; }
let c = LOAD(autoTex, vec2i(m % 16, m / 16) * 16 + tex);`,
      },
    ],
    links: [
      { title: 'Boris the Brave — classification of tilesets', url: 'https://www.boristhebrave.com/2021/11/14/classification-of-tilesets/', note: 'blob, Wang and corner tilesets' },
    ],
  },

  async init(ctx) {
    const gpu = ctx.gpu;
    const { atlas, view: atlasView } = await atlasTexture(gpu);
    const tileset = buildTileset(atlas);
    const tilesTex = gpu.textureFromImage(tileset.canvas, { label: 'tileset' });
    const autoTex = gpu.textureFromImage(buildAutotiles(atlas), { label: 'autotiles' });

    const U = gpu.uniforms(
      {
        res: 'vec2f',
        cam: 'vec2f',
        mapSize: 'vec2f',
        hover: 'vec2f',
        zoom: 'f32',
        time: 'f32',
        mode: 'f32',
        grid: 'f32',
        ids: 'f32',
        anim: 'f32',
        foam: 'f32',
        autoMode: 'f32',
        lod: 'f32',
        avg: 'array<vec4f, 32>',
      },
      'Tiles',
    );
    U.set('avg', tileset.avg);
    const fx = gpu.fullscreen({ label: 'tilemap', code: MAP_WGSL, uniforms: U, textures: ['map', 'tiles', 'autoTex'], include: ['hash'] });

    // ---- RPG map (CPU generated, small) ----
    const RW = 128;
    const RH = 96;
    let rpg = null;
    let rpgTex = null;
    const makeRpg = (seed) => {
      rpg = buildRpgMap(RW, RH, seed);
      rpgTex?.destroy();
      rpgTex = gpu.textureFromData(RW, RH, rpg.data, { label: 'rpg-map' });
      rpg.trees.sort((a, b) => a[1] - b[1]);
    };

    // ---- side-scroller map (edited live) ----
    const SW = 64;
    const SH = 16;
    let side = buildSideMap(SW, SH);
    const sideTex = gpu.texture({ size: [SW, SH], format: 'rgba8unorm', label: 'side-map' });
    const sideBytes = new Uint8Array(SW * SH * 4);
    const uploadSide = () => {
      for (let i = 0; i < SW * SH; i++) {
        sideBytes[i * 4] = side[i];
        sideBytes[i * 4 + 3] = 255;
      }
      gpu.queue.writeTexture({ texture: sideTex }, sideBytes, { bytesPerRow: SW * 4 }, [SW, SH]);
    };
    uploadSide();

    // ---- huge map (compute generated) ----
    const G = gpu.uniforms({ size: 'f32', seed: 'f32' }, 'Gen');
    const gen = gpu.compute({ label: 'map-gen', bindings: { g: { uniform: G }, outTex: { storageTexture: 'rgba8unorm', access: 'write' } }, include: ['noise'], code: GEN_WGSL });
    let huge = null;
    let hugeSize = 0;
    let genMs = 0;
    let genBusy = false;
    const makeHuge = (size, seed) => {
      if (genBusy) return;
      if (!huge || hugeSize !== size) {
        huge?.destroy();
        huge = gpu.target(size, size, { format: 'rgba8unorm', label: 'huge-map' });
        hugeSize = size;
      }
      G.set('size', size).set('seed', seed);
      G.upload();
      const enc = gpu.device.createCommandEncoder();
      const t0 = performance.now();
      gen.dispatch(enc, 'gen', [Math.ceil(size / 8), Math.ceil(size / 8)], { g: G, outTex: huge });
      gpu.queue.submit([enc.finish()]);
      genBusy = true;
      gpu.queue.onSubmittedWorkDone().then(() => {
        genMs = performance.now() - t0;
        genBusy = false;
      });
    };

    const trees = new SpriteBatch(gpu, { texture: atlasView, filter: 'nearest' });
    const cam = new Camera2D();
    const readout = tag(ctx, 'right:8px;top:48px;text-align:right;line-height:1.5');

    // per-example camera state
    const views = {
      rpg: { x: RW * 8, y: RH * 8, zoom: ctx.params.zoom },
      autotile: { x: 0, y: 0, zoom: 2 },
      huge: { x: 2048 * 16, y: 2048 * 16, zoom: ctx.params.zoom },
    };
    let rpgSeed = null;
    let hugeSeed = null;
    let hugeWanted = 0;

    const ensureMaps = (p) => {
      if (ctx.example === 'rpg' && (!rpg || rpgSeed !== p.seed)) {
        makeRpg(p.seed);
        rpgSeed = p.seed;
        // start somewhere interesting: the window with the most variety (water, sand, forest, trees…)
        let best = -1;
        for (let cy = 8; cy < RH - 8; cy += 4)
          for (let cx = 12; cx < RW - 12; cx += 4) {
            const kinds = new Set();
            let water = 0;
            for (let y = cy - 6; y <= cy + 6; y += 2)
              for (let x = cx - 10; x <= cx + 10; x += 2) {
                const id = rpg.data[(y * RW + x) * 4];
                kinds.add(id);
                if (id >= 8 && id < 16) water++;
              }
            const score = kinds.size * 10 - Math.abs(water - 18);
            if (score > best) {
              best = score;
              views.rpg.x = cx * 16 + 8;
              views.rpg.y = cy * 16 + 8;
            }
          }
      }
      if (ctx.example === 'huge') {
        const size = ctx.testMode ? 1024 : +p.mapSize;
        if ((!huge || hugeWanted !== size || hugeSeed !== p.seed) && !genBusy) {
          if (huge && hugeSize !== size) {
            views.huge.x *= size / hugeSize;
            views.huge.y *= size / hugeSize;
          } else if (!huge) {
            views.huge.x = size * 8;
            views.huge.y = size * 8;
          }
          makeHuge(size, p.seed);
          hugeWanted = size;
          hugeSeed = p.seed;
        }
      }
    };

    return {
      onAction(key) {
        if (key === 'reset') {
          side = buildSideMap(SW, SH);
          uploadSide();
        }
      },
      onChange(key, v) {
        if (key === 'zoom' && views[ctx.example]) views[ctx.example].zoom = v;
      },
      frame(ctx) {
        const p = ctx.params;
        const ex = ctx.example;
        ensureMaps(p);
        const W = ctx.width;
        const H = ctx.height;
        const ptr = ctx.pointer;
        const v = views[ex];
        let mapSize = [RW, RH];
        let mapTex = rpgTex;
        let mode = 0;
        if (ex === 'autotile') {
          mode = 1;
          mapSize = [SW, SH];
          mapTex = sideTex;
          v.zoom = Math.max(1, Math.round(H / (12.5 * TS)));
          const viewW = W / v.zoom;
          const scroll = (ctx.keys.has('ArrowRight') || ctx.keys.has('d') ? 1 : 0) - (ctx.keys.has('ArrowLeft') || ctx.keys.has('a') ? 1 : 0);
          if (v.x === 0) v.x = viewW / 2;
          v.x = clamp(v.x + scroll * 300 * ctx.dt, viewW / 2, Math.max(viewW / 2, SW * TS - viewW / 2));
          v.y = SH * TS - H / v.zoom / 2;
        } else if (ex === 'huge') {
          mode = 2;
          mapSize = [hugeSize, hugeSize];
          mapTex = huge;
        }
        // ---- pan & zoom (v.zoom is in CSS px per texel; Z in device px) ----
        let Z = mode === 1 ? v.zoom : v.zoom * ctx.dpr;
        if (mode !== 1) {
          if (ptr.down && (ptr.dx || ptr.dy)) {
            v.x -= ptr.dx / Z;
            v.y -= ptr.dy / Z;
          }
          if (ptr.wheel) {
            const before = [v.x + (ptr.x - W / 2) / Z, v.y + (ptr.y - H / 2) / Z];
            v.zoom = clamp(v.zoom * Math.exp(-ptr.wheel * 0.0015), mode === 2 ? 0.004 : 0.3, 12);
            Z = v.zoom * ctx.dpr;
            v.x = before[0] - (ptr.x - W / 2) / Z;
            v.y = before[1] - (ptr.y - H / 2) / Z;
          }
          const ext = [mapSize[0] * TS, mapSize[1] * TS];
          v.x = clamp(v.x, 0, ext[0]);
          v.y = clamp(v.y, 0, ext[1]);
        }
        const wx = v.x + (ptr.x - W / 2) / Z;
        const wy = v.y + (ptr.y - H / 2) / Z;
        const hx = Math.floor(wx / TS);
        const hy = Math.floor(wy / TS);
        const hoverIn = ptr.over && hx >= 0 && hy >= 0 && hx < mapSize[0] && hy < mapSize[1];

        // ---- painting (autotile) ----
        if (mode === 1 && ptr.down && hoverIn) {
          const val = ptr.button === 2 || p.brush === 'erase' ? 0 : 1;
          if (side[hy * SW + hx] !== val) {
            side[hy * SW + hx] = val;
            uploadSide();
          }
        }

        U.set('res', [W, H])
          .set('cam', [v.x, v.y])
          .set('zoom', Z)
          .set('time', ctx.time)
          .set('mode', mode)
          .set('mapSize', mapSize)
          .set('hover', hoverIn ? [hx, hy] : [-9, -9])
          .set('grid', p.grid ? 1 : 0)
          .set('ids', p.ids ? 1 : 0)
          .set('anim', p.anim ? 1 : 0)
          .set('foam', p.foam ? 1 : 0)
          .set('autoMode', p.auto === 'off' ? 0 : p.auto === '4' ? 1 : 2)
          .set('lod', mode === 2 ? (p.lod ? 1 : 0) : 0);
        const canvas = { view: ctx.target, format: gpu.format };
        fx.draw(ctx.encoder, canvas, { map: mapTex, tiles: tilesTex, autoTex });

        // ---- tree objects (taller than a tile → sprites, sorted by their feet) ----
        let treeCount = 0;
        if (mode === 0 && p.trees) {
          cam.setViewport(W, H);
          cam.x = v.x;
          cam.y = v.y;
          cam.zoom = Z;
          trees.begin();
          const x0 = v.x - W / 2 / Z - 32;
          const x1 = v.x + W / 2 / Z + 32;
          const y0 = v.y - H / 2 / Z - 16;
          const y1 = v.y + H / 2 / Z + 64;
          const uv = atlas.uv('tree');
          for (const [tx, ty] of rpg.trees) {
            const x = tx * TS + 8;
            const y = ty * TS + 14;
            if (x < x0 || x > x1 || y < y0 || y > y1) continue;
            trees.draw(x, y, 32, 48, { uv, anchor: [0.5, 1] });
            treeCount++;
          }
          trees.flush(ctx.encoder, canvas, cam);
        }

        // ---- readout ----
        const visTiles = Math.ceil(W / Z / TS + 1) * Math.ceil(H / Z / TS + 1);
        let hoverTxt = '';
        if (hoverIn && mode === 0) {
          const id = rpg.data[(hy * RW + hx) * 4];
          const deco = rpg.data[(hy * RW + hx) * 4 + 1];
          hoverTxt = `<br>tile (${hx}, ${hy}) → id <b style="color:#fcd34d">${id}</b> ${NAMES[id] || ''}${deco ? ` + ${NAMES[deco]}` : ''}`;
        }
        if (hoverIn && mode === 1) {
          const s = (x, y) => (y >= SH ? 1 : y < 0 ? 0 : side[y * SW + clamp(x, 0, SW - 1)]);
          if (s(hx, hy)) {
            const n = s(hx, hy - 1);
            const e = s(hx + 1, hy);
            const so = s(hx, hy + 1);
            const w = s(hx - 1, hy);
            let m = n + 2 * e + 4 * so + 8 * w;
            const parts = [n && 'N1', e && 'E2', so && 'S4', w && 'W8'].filter(Boolean);
            if (p.auto === '8') {
              if (n && e && s(hx + 1, hy - 1)) (m += 16), parts.push('NE16');
              if (so && e && s(hx + 1, hy + 1)) (m += 32), parts.push('SE32');
              if (so && w && s(hx - 1, hy + 1)) (m += 64), parts.push('SW64');
              if (n && w && s(hx - 1, hy - 1)) (m += 128), parts.push('NW128');
            }
            hoverTxt = p.auto === 'off' ? '<br>autotiling off: always the same tile' : `<br>mask = ${parts.join(' + ') || '0'} = <b style="color:#fcd34d">${m}</b>`;
          } else hoverTxt = '<br>empty tile (not drawn)';
        }
        if (mode === 0)
          readout.innerHTML = `map ${RW}×${RH} tiles · ground layer: <b style="color:#86efac">1 draw call</b><br>trees: ${treeCount} sprites, 1 draw call${hoverTxt}`;
        else if (mode === 1)
          readout.innerHTML = `${p.auto === 'off' ? '1 tile' : p.auto === '4' ? '16 tiles (4-bit)' : '47 tiles (8-bit blob)'} · <b style="color:#86efac">1 draw call</b>${hoverTxt}`;
        else
          readout.innerHTML =
            `<b style="color:#fcd34d">${fmt(hugeSize * hugeSize)} tiles</b> (${hugeSize}²) · <b style="color:#86efac">1 draw call</b><br>` +
            `generated by compute in ${genBusy ? '…' : genMs.toFixed(1) + ' ms'} · ~${fmt(Math.min(visTiles, hugeSize * hugeSize))} tiles visible<br>` +
            `tile = ${(16 * Z).toFixed(2)} px on screen${16 * Z < 5 && p.lod ? ' → LOD: average colours' : ''}`;
      },
    };
  },
};
